# coding: utf-8

"""
    PostBoost API

    The PostBoost REST API lets you publish, schedule, and analyze social media posts across 8+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

    The version of the OpenAPI document: 1.0.0
    Contact: hi@postboost.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from postboost.api.posts_api import PostsApi


class TestPostsApi(unittest.TestCase):
    """PostsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PostsApi()

    def tearDown(self) -> None:
        pass

    def test_add_post_to_queue(self) -> None:
        """Test case for add_post_to_queue

        Add post to queue
        """
        pass

    def test_approve_post(self) -> None:
        """Test case for approve_post

        Approve post
        """
        pass

    def test_create_post(self) -> None:
        """Test case for create_post

        Create post
        """
        pass

    def test_delete_post(self) -> None:
        """Test case for delete_post

        Delete post
        """
        pass

    def test_delete_posts_bulk(self) -> None:
        """Test case for delete_posts_bulk

        Delete posts (bulk)
        """
        pass

    def test_get_post(self) -> None:
        """Test case for get_post

        Get post
        """
        pass

    def test_list_posts(self) -> None:
        """Test case for list_posts

        List posts
        """
        pass

    def test_schedule_post(self) -> None:
        """Test case for schedule_post

        Schedule post
        """
        pass

    def test_update_post(self) -> None:
        """Test case for update_post

        Update post
        """
        pass


if __name__ == '__main__':
    unittest.main()
