# coding: utf-8

"""
    PostBoost API

    The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

    The version of the OpenAPI document: 1.0.0
    Contact: hi@postboost.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from postboost.models.blog_to_social_input import BlogToSocialInput

class TestBlogToSocialInput(unittest.TestCase):
    """BlogToSocialInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BlogToSocialInput:
        """Test BlogToSocialInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BlogToSocialInput`
        """
        model = BlogToSocialInput()
        if include_optional:
            return BlogToSocialInput(
                url = 'https://example.com/blog/my-post',
                title = '10 Tips for Better Social Media',
                excerpt = 'Social media success starts with consistency and knowing your audience...',
                image_url = 'https://example.com/images/post-cover.jpg',
                platforms = [x, linkedin],
                account_ids = [5, 12],
                tone = 'engaging',
                content_length = 'medium',
                hashtags = 'few',
                cta = 'none',
                language = 'auto',
                custom_instructions = 'Always mention that PostBoost supports 12+ platforms.',
                create_post = True
            )
        else:
            return BlogToSocialInput(
        )
        """

    def testBlogToSocialInput(self):
        """Test BlogToSocialInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
