# coding: utf-8

"""
    PostBoost API

    The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

    The version of the OpenAPI document: 1.0.0
    Contact: hi@postboost.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from postboost.models.image_edit_input import ImageEditInput

class TestImageEditInput(unittest.TestCase):
    """ImageEditInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImageEditInput:
        """Test ImageEditInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImageEditInput`
        """
        model = ImageEditInput()
        if include_optional:
            return ImageEditInput(
                media_uuid = '',
                prompt = 'Make the background a white studio backdrop',
                mask_uuid = '',
                aspect_ratio = '1:1',
                count = 1,
                quality = 'standard'
            )
        else:
            return ImageEditInput(
                media_uuid = '',
                prompt = 'Make the background a white studio backdrop',
        )
        """

    def testImageEditInput(self):
        """Test ImageEditInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
