# coding: utf-8

"""
    PostBoost API

    The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

    The version of the OpenAPI document: 1.0.0
    Contact: hi@postboost.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from postboost.models.blog_to_social200_response import BlogToSocial200Response

class TestBlogToSocial200Response(unittest.TestCase):
    """BlogToSocial200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BlogToSocial200Response:
        """Test BlogToSocial200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BlogToSocial200Response`
        """
        model = BlogToSocial200Response()
        if include_optional:
            return BlogToSocial200Response(
                data = postboost.models.blog_to_social_response.BlogToSocialResponse(
                    blog_title = '10 Tips for Better Social Media', 
                    blog_excerpt = 'Social media success starts with consistency...', 
                    captions = [
                        postboost.models.blog_to_social_caption.BlogToSocialCaption(
                            account_id = 5, 
                            provider = 'x', 
                            content = 'Unlock better social media results with these 10 proven tips. #SocialMedia #Marketing', 
                            character_count = 87, 
                            character_limit = 280, 
                            error = '', )
                        ], 
                    post_uuid = '01942c3d-1234-7abc-8ef0-1234567890ab', 
                    media = postboost.models.blog_to_social_media.BlogToSocialMedia(
                        id = 42, 
                        url = 'https://postboost.co/storage/workspaces/1/blog-images/2026/04/cover.jpg', ), 
                    credits_used = 3, 
                    credits_remaining = 37, )
            )
        else:
            return BlogToSocial200Response(
        )
        """

    def testBlogToSocial200Response(self):
        """Test BlogToSocial200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
