# coding: utf-8

"""
    PostBoost API

    The PostBoost REST API lets you publish, schedule, and analyze social media posts across 8+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

    The version of the OpenAPI document: 1.0.0
    Contact: hi@postboost.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from postboost.api.subscriptions_api import SubscriptionsApi


class TestSubscriptionsApi(unittest.TestCase):
    """SubscriptionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SubscriptionsApi()

    def tearDown(self) -> None:
        pass

    def test_add_generic_subscription(self) -> None:
        """Test case for add_generic_subscription

        Add generic subscription
        """
        pass

    def test_cancel_subscription(self) -> None:
        """Test case for cancel_subscription

        Cancel subscription
        """
        pass

    def test_change_subscription_plan(self) -> None:
        """Test case for change_subscription_plan

        Change subscription plan
        """
        pass

    def test_checkout_subscription(self) -> None:
        """Test case for checkout_subscription

        New subscription checkout
        """
        pass

    def test_create_subscription(self) -> None:
        """Test case for create_subscription

        Create subscription
        """
        pass

    def test_delete_subscription(self) -> None:
        """Test case for delete_subscription

        Delete subscription
        """
        pass

    def test_get_subscription(self) -> None:
        """Test case for get_subscription

        Get subscription
        """
        pass

    def test_remove_generic_subscription(self) -> None:
        """Test case for remove_generic_subscription

        Remove generic subscription
        """
        pass

    def test_resume_subscription(self) -> None:
        """Test case for resume_subscription

        Resume subscription
        """
        pass

    def test_update_subscription(self) -> None:
        """Test case for update_subscription

        Update subscription
        """
        pass


if __name__ == '__main__':
    unittest.main()
