# coding: utf-8

"""
    PostBoost API

    The PostBoost REST API lets you publish, schedule, and analyze social media posts across 8+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

    The version of the OpenAPI document: 1.0.0
    Contact: hi@postboost.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from postboost.api.tags_api import TagsApi


class TestTagsApi(unittest.TestCase):
    """TagsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TagsApi()

    def tearDown(self) -> None:
        pass

    def test_create_tag(self) -> None:
        """Test case for create_tag

        Create tag
        """
        pass

    def test_delete_tag(self) -> None:
        """Test case for delete_tag

        Delete tag
        """
        pass

    def test_get_tag(self) -> None:
        """Test case for get_tag

        Get tag
        """
        pass

    def test_list_tags(self) -> None:
        """Test case for list_tags

        List tags
        """
        pass

    def test_update_tag(self) -> None:
        """Test case for update_tag

        Update tag
        """
        pass


if __name__ == '__main__':
    unittest.main()
