# coding: utf-8

"""
    PostBoost API

    The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

    The version of the OpenAPI document: 1.0.0
    Contact: hi@postboost.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from postboost.api.receipts_api import ReceiptsApi


class TestReceiptsApi(unittest.TestCase):
    """ReceiptsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ReceiptsApi()

    def tearDown(self) -> None:
        pass

    def test_create_receipt(self) -> None:
        """Test case for create_receipt

        Create receipt
        """
        pass

    def test_delete_receipt(self) -> None:
        """Test case for delete_receipt

        Delete receipt
        """
        pass

    def test_delete_receipts_bulk(self) -> None:
        """Test case for delete_receipts_bulk

        Delete receipts (bulk)
        """
        pass

    def test_get_receipt(self) -> None:
        """Test case for get_receipt

        Get receipt
        """
        pass

    def test_list_receipts(self) -> None:
        """Test case for list_receipts

        List receipts
        """
        pass

    def test_update_receipt(self) -> None:
        """Test case for update_receipt

        Update receipt
        """
        pass


if __name__ == '__main__':
    unittest.main()
