# coding: utf-8

"""
    PostBoost API

    The PostBoost REST API lets you publish, schedule, and analyze social media posts across 8+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

    The version of the OpenAPI document: 1.0.0
    Contact: hi@postboost.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from postboost.api.media_api import MediaApi


class TestMediaApi(unittest.TestCase):
    """MediaApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MediaApi()

    def tearDown(self) -> None:
        pass

    def test_abort_chunked_upload(self) -> None:
        """Test case for abort_chunked_upload

        Abort chunked upload
        """
        pass

    def test_complete_chunked_upload(self) -> None:
        """Test case for complete_chunked_upload

        Complete chunked upload
        """
        pass

    def test_delete_media_bulk(self) -> None:
        """Test case for delete_media_bulk

        Delete media (bulk)
        """
        pass

    def test_get_media(self) -> None:
        """Test case for get_media

        Get media
        """
        pass

    def test_get_remote_upload_status(self) -> None:
        """Test case for get_remote_upload_status

        Get remote upload status
        """
        pass

    def test_initiate_chunked_upload(self) -> None:
        """Test case for initiate_chunked_upload

        Initiate chunked upload
        """
        pass

    def test_initiate_remote_upload(self) -> None:
        """Test case for initiate_remote_upload

        Initiate remote upload
        """
        pass

    def test_list_media(self) -> None:
        """Test case for list_media

        List media
        """
        pass

    def test_update_media(self) -> None:
        """Test case for update_media

        Update media
        """
        pass

    def test_upload_chunk(self) -> None:
        """Test case for upload_chunk

        Upload a chunk
        """
        pass

    def test_upload_media(self) -> None:
        """Test case for upload_media

        Upload media (binary)
        """
        pass


if __name__ == '__main__':
    unittest.main()
