# coding: utf-8

"""
    PostBoost API

    The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

    The version of the OpenAPI document: 1.0.0
    Contact: hi@postboost.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from postboost.api.ai_api import AIApi


class TestAIApi(unittest.TestCase):
    """AIApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AIApi()

    def tearDown(self) -> None:
        pass

    def test_blog_to_social(self) -> None:
        """Test case for blog_to_social

        Generate social media captions from a blog post
        """
        pass

    def test_image_alt_text(self) -> None:
        """Test case for image_alt_text

        Generate alt text for a media image using AI
        """
        pass

    def test_image_edit(self) -> None:
        """Test case for image_edit

        Edit an existing media image using AI
        """
        pass

    def test_image_generate(self) -> None:
        """Test case for image_generate

        Generate social media images from a caption
        """
        pass

    def test_image_prompt(self) -> None:
        """Test case for image_prompt

        Build an optimized image prompt from a social media caption
        """
        pass

    def test_image_variations(self) -> None:
        """Test case for image_variations

        Generate variations of an existing media image
        """
        pass


if __name__ == '__main__':
    unittest.main()
