# coding: utf-8

"""
    PostBoost API

    The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

    The version of the OpenAPI document: 1.0.0
    Contact: hi@postboost.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from postboost.models.pagination_meta import PaginationMeta

class TestPaginationMeta(unittest.TestCase):
    """PaginationMeta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginationMeta:
        """Test PaginationMeta
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginationMeta`
        """
        model = PaginationMeta()
        if include_optional:
            return PaginationMeta(
                links = postboost.models.pagination_meta_links.PaginationMeta_links(
                    first = '', 
                    last = '', 
                    prev = '', 
                    next = '', ),
                meta = postboost.models.pagination_meta_meta.PaginationMeta_meta(
                    current_page = 56, 
                    from = 56, 
                    last_page = 56, 
                    per_page = 56, 
                    to = 56, 
                    total = 56, )
            )
        else:
            return PaginationMeta(
        )
        """

    def testPaginationMeta(self):
        """Test PaginationMeta"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
