# coding: utf-8

"""
    PostBoost API

    The PostBoost REST API lets you publish, schedule, and analyze social media posts across 8+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

    The version of the OpenAPI document: 1.0.0
    Contact: hi@postboost.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from postboost.models.initiate_remote_upload200_response import InitiateRemoteUpload200Response

class TestInitiateRemoteUpload200Response(unittest.TestCase):
    """InitiateRemoteUpload200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InitiateRemoteUpload200Response:
        """Test InitiateRemoteUpload200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InitiateRemoteUpload200Response`
        """
        model = InitiateRemoteUpload200Response()
        if include_optional:
            return InitiateRemoteUpload200Response(
                id = 56,
                uuid = '',
                name = '',
                mime_type = 'image/jpeg',
                type = 'image',
                url = '',
                thumb_url = '',
                is_video = True,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                download_id = ''
            )
        else:
            return InitiateRemoteUpload200Response(
        )
        """

    def testInitiateRemoteUpload200Response(self):
        """Test InitiateRemoteUpload200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
