# coding: utf-8

"""
    PostBoost API

    The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

    The version of the OpenAPI document: 1.0.0
    Contact: hi@postboost.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from postboost.models.change_subscription_plan_request import ChangeSubscriptionPlanRequest

class TestChangeSubscriptionPlanRequest(unittest.TestCase):
    """ChangeSubscriptionPlanRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChangeSubscriptionPlanRequest:
        """Test ChangeSubscriptionPlanRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChangeSubscriptionPlanRequest`
        """
        model = ChangeSubscriptionPlanRequest()
        if include_optional:
            return ChangeSubscriptionPlanRequest(
                plan_id = 56,
                cycle = 'monthly',
                prorate = True,
                billing_immediately = True
            )
        else:
            return ChangeSubscriptionPlanRequest(
                plan_id = 56,
                cycle = 'monthly',
                prorate = True,
                billing_immediately = True,
        )
        """

    def testChangeSubscriptionPlanRequest(self):
        """Test ChangeSubscriptionPlanRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
