# coding: utf-8

"""
    PostBoost API

    The PostBoost REST API lets you publish, schedule, and analyze social media posts across 8+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

    The version of the OpenAPI document: 1.0.0
    Contact: hi@postboost.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "postboost"
VERSION = "1.0.0"
PYTHON_REQUIRES = ">= 3.8"
REQUIRES = [
    "urllib3 >= 1.25.3, < 3.0.0",
    "python-dateutil >= 2.8.2",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="PostBoost API",
    author="PostBoost Support",
    author_email="hi@postboost.co",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "PostBoost API"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    license="Commercial",
    long_description_content_type='text/markdown',
    long_description="""\
    The PostBoost REST API lets you publish, schedule, and analyze social media posts across 8+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with &#x60;/{workspaceUuid}&#x60;. Panel/admin endpoints are prefixed with &#x60;/panel&#x60;.  ## Authentication All requests require a Bearer token in the &#x60;Authorization&#x60; header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  &#x60;&#x60;&#x60; Authorization: Bearer YOUR_API_TOKEN &#x60;&#x60;&#x60; 
    """,  # noqa: E501
    package_data={"postboost": ["py.typed"]},
)
