# coding: utf-8

"""
    PostBoost API

    The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

    The version of the OpenAPI document: 1.0.0
    Contact: hi@postboost.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class BlogToSocialInput(BaseModel):
    """
    At least one of `url` or (`title` + `excerpt`) must be provided. If both are given, direct values take priority over the scraped URL content. 
    """ # noqa: E501
    url: Optional[Annotated[str, Field(strict=True, max_length=2000)]] = Field(default=None, description="Blog post URL to scrape. Required if `title` and `excerpt` are not provided.")
    title: Optional[Annotated[str, Field(strict=True, max_length=500)]] = Field(default=None, description="Blog post title. Required if `url` is not provided.")
    excerpt: Optional[Annotated[str, Field(strict=True, max_length=5000)]] = Field(default=None, description="Blog post summary or excerpt. Required if `url` is not provided.")
    image_url: Optional[Annotated[str, Field(strict=True, max_length=2000)]] = Field(default=None, description="Featured image URL for the blog post. When `create_post` is `true`, the image is imported into the workspace media library and attached to the draft post. If omitted in URL mode, the scraper attempts to extract the `og:image` meta tag. ")
    platforms: Optional[List[StrictStr]] = Field(default=None, description="Target social media platforms. Only connected accounts matching these platforms are used. If omitted, all connected accounts in the workspace are targeted. ")
    account_ids: Optional[List[StrictInt]] = Field(default=None, description="Specific account IDs to generate captions for. Takes precedence over `platforms` when both are provided. ")
    tone: Optional[StrictStr] = Field(default='engaging', description="Writing tone for all generated captions.")
    content_length: Optional[StrictStr] = Field(default='medium', description="Desired length of the generated captions.")
    hashtags: Optional[StrictStr] = Field(default='few', description="Hashtag quantity: none (0), few (1-3), some (3-5), many (5+).")
    cta: Optional[StrictStr] = Field(default='none', description="Call-to-action type appended to each caption.")
    language: Optional[Annotated[str, Field(strict=True, max_length=10)]] = Field(default='auto', description="Output language as an ISO 639-1 code (e.g. `en`, `de`, `fr`). Use `auto` to match the blog post's language automatically. ")
    custom_instructions: Optional[Annotated[str, Field(strict=True, max_length=500)]] = Field(default=None, description="Additional instructions appended to the AI prompt (e.g. \"always mention our free tier\").")
    create_post: Optional[StrictBool] = Field(default=False, description="When `true`, creates a draft post in the workspace with per-account caption versions. If an image is available, it is imported and attached to the post. ")
    __properties: ClassVar[List[str]] = ["url", "title", "excerpt", "image_url", "platforms", "account_ids", "tone", "content_length", "hashtags", "cta", "language", "custom_instructions", "create_post"]

    @field_validator('platforms')
    def platforms_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['facebook', 'instagram', 'x', 'linkedin', 'pinterest', 'youtube', 'tiktok', 'mastodon', 'threads', 'bluesky', 'google_business']):
                raise ValueError("each list item must be one of ('facebook', 'instagram', 'x', 'linkedin', 'pinterest', 'youtube', 'tiktok', 'mastodon', 'threads', 'bluesky', 'google_business')")
        return value

    @field_validator('tone')
    def tone_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['neutral', 'friendly', 'formal', 'edgy', 'engaging', 'casual', 'professional', 'humorous', 'inspirational', 'conversational']):
            raise ValueError("must be one of enum values ('neutral', 'friendly', 'formal', 'edgy', 'engaging', 'casual', 'professional', 'humorous', 'inspirational', 'conversational')")
        return value

    @field_validator('content_length')
    def content_length_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['short', 'medium', 'long']):
            raise ValueError("must be one of enum values ('short', 'medium', 'long')")
        return value

    @field_validator('hashtags')
    def hashtags_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['none', 'few', 'some', 'many']):
            raise ValueError("must be one of enum values ('none', 'few', 'some', 'many')")
        return value

    @field_validator('cta')
    def cta_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['none', 'question', 'link', 'subscribe', 'follow', 'share', 'learn_more', 'signup', 'buy', 'download']):
            raise ValueError("must be one of enum values ('none', 'question', 'link', 'subscribe', 'follow', 'share', 'learn_more', 'signup', 'buy', 'download')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BlogToSocialInput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BlogToSocialInput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "url": obj.get("url"),
            "title": obj.get("title"),
            "excerpt": obj.get("excerpt"),
            "image_url": obj.get("image_url"),
            "platforms": obj.get("platforms"),
            "account_ids": obj.get("account_ids"),
            "tone": obj.get("tone") if obj.get("tone") is not None else 'engaging',
            "content_length": obj.get("content_length") if obj.get("content_length") is not None else 'medium',
            "hashtags": obj.get("hashtags") if obj.get("hashtags") is not None else 'few',
            "cta": obj.get("cta") if obj.get("cta") is not None else 'none',
            "language": obj.get("language") if obj.get("language") is not None else 'auto',
            "custom_instructions": obj.get("custom_instructions"),
            "create_post": obj.get("create_post") if obj.get("create_post") is not None else False
        })
        return _obj


