# coding: utf-8

"""
    PostBoost API

    The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

    The version of the OpenAPI document: 1.0.0
    Contact: hi@postboost.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from postboost.models.blog_to_social_caption import BlogToSocialCaption
from postboost.models.blog_to_social_media import BlogToSocialMedia
from typing import Optional, Set
from typing_extensions import Self

class BlogToSocialResponse(BaseModel):
    """
    BlogToSocialResponse
    """ # noqa: E501
    blog_title: Optional[StrictStr] = Field(default=None, description="The blog post title (scraped or provided directly).")
    blog_excerpt: Optional[StrictStr] = Field(default=None, description="A short excerpt from the blog post content.")
    captions: Optional[List[BlogToSocialCaption]] = Field(default=None, description="Generated captions, one per target account.")
    post_uuid: Optional[StrictStr] = Field(default=None, description="UUID of the created draft post. Only present when `create_post` was `true`.")
    media: Optional[BlogToSocialMedia] = None
    credits_used: Optional[StrictInt] = Field(default=None, description="Number of AI credits consumed by this request (one per successful caption).")
    credits_remaining: Optional[StrictInt] = Field(default=None, description="Remaining AI credits for the current billing period. `null` for unlimited plans.")
    __properties: ClassVar[List[str]] = ["blog_title", "blog_excerpt", "captions", "post_uuid", "media", "credits_used", "credits_remaining"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BlogToSocialResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in captions (list)
        _items = []
        if self.captions:
            for _item_captions in self.captions:
                if _item_captions:
                    _items.append(_item_captions.to_dict())
            _dict['captions'] = _items
        # override the default output from pydantic by calling `to_dict()` of media
        if self.media:
            _dict['media'] = self.media.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BlogToSocialResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "blog_title": obj.get("blog_title"),
            "blog_excerpt": obj.get("blog_excerpt"),
            "captions": [BlogToSocialCaption.from_dict(_item) for _item in obj["captions"]] if obj.get("captions") is not None else None,
            "post_uuid": obj.get("post_uuid"),
            "media": BlogToSocialMedia.from_dict(obj["media"]) if obj.get("media") is not None else None,
            "credits_used": obj.get("credits_used"),
            "credits_remaining": obj.get("credits_remaining")
        })
        return _obj


