# coding: utf-8

"""
    PostBoost API

    The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

    The version of the OpenAPI document: 1.0.0
    Contact: hi@postboost.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class DeleteMode(str, Enum):
    """
    - `app_only` — delete from PostBoost only - `app_and_social` — delete from PostBoost and the social platform - `social_only` — delete from the social platform only 
    """

    """
    allowed enum values
    """
    APP_ONLY = 'app_only'
    APP_AND_SOCIAL = 'app_and_social'
    SOCIAL_ONLY = 'social_only'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DeleteMode from a JSON string"""
        return cls(json.loads(json_str))


