# coding: utf-8

"""
    PostBoost API

    The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

    The version of the OpenAPI document: 1.0.0
    Contact: hi@postboost.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class ImageGenerateInput(BaseModel):
    """
    ImageGenerateInput
    """ # noqa: E501
    caption: Optional[Annotated[str, Field(strict=True, max_length=2000)]] = Field(default=None, description="Social media caption. Triggers standard mode. Takes priority over prompt.")
    platform: Optional[StrictStr] = Field(default=None, description="Required when caption is provided.")
    template: Optional[StrictStr] = None
    style: Optional[StrictStr] = None
    brand_voice: Optional[StrictStr] = None
    custom_instructions: Optional[Annotated[str, Field(strict=True, max_length=1000)]] = None
    prompt: Optional[Annotated[str, Field(strict=True, max_length=4000)]] = Field(default=None, description="Developer escape hatch. Bypasses internal prompt builder. Ignored if caption is present.")
    aspect_ratio: Optional[StrictStr] = '1:1'
    count: Optional[Annotated[int, Field(le=4, strict=True, ge=1)]] = 1
    quality: Optional[StrictStr] = 'standard'
    __properties: ClassVar[List[str]] = ["caption", "platform", "template", "style", "brand_voice", "custom_instructions", "prompt", "aspect_ratio", "count", "quality"]

    @field_validator('template')
    def template_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['blog_cover', 'quote_card', 'stat_card', 'feature_announcement', 'product_highlight', 'event_promo', 'carousel_slide', 'ad_creative']):
            raise ValueError("must be one of enum values ('blog_cover', 'quote_card', 'stat_card', 'feature_announcement', 'product_highlight', 'event_promo', 'carousel_slide', 'ad_creative')")
        return value

    @field_validator('aspect_ratio')
    def aspect_ratio_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['1:1', '16:9', '9:16', '4:5']):
            raise ValueError("must be one of enum values ('1:1', '16:9', '9:16', '4:5')")
        return value

    @field_validator('quality')
    def quality_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['standard', 'hd']):
            raise ValueError("must be one of enum values ('standard', 'hd')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ImageGenerateInput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ImageGenerateInput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "caption": obj.get("caption"),
            "platform": obj.get("platform"),
            "template": obj.get("template"),
            "style": obj.get("style"),
            "brand_voice": obj.get("brand_voice"),
            "custom_instructions": obj.get("custom_instructions"),
            "prompt": obj.get("prompt"),
            "aspect_ratio": obj.get("aspect_ratio") if obj.get("aspect_ratio") is not None else '1:1',
            "count": obj.get("count") if obj.get("count") is not None else 1,
            "quality": obj.get("quality") if obj.get("quality") is not None else 'standard'
        })
        return _obj


