# coding: utf-8

"""
    PostBoost API

    The PostBoost REST API lets you publish, schedule, and analyze social media posts across 8+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

    The version of the OpenAPI document: 1.0.0
    Contact: hi@postboost.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from postboost.models.initiate_remote_upload201_response_one_of import InitiateRemoteUpload201ResponseOneOf
from postboost.models.media import Media
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

INITIATEREMOTEUPLOAD201RESPONSE_ONE_OF_SCHEMAS = ["InitiateRemoteUpload201ResponseOneOf", "Media"]

class InitiateRemoteUpload201Response(BaseModel):
    """
    InitiateRemoteUpload201Response
    """
    # data type: Media
    oneof_schema_1_validator: Optional[Media] = None
    # data type: InitiateRemoteUpload201ResponseOneOf
    oneof_schema_2_validator: Optional[InitiateRemoteUpload201ResponseOneOf] = None
    actual_instance: Optional[Union[InitiateRemoteUpload201ResponseOneOf, Media]] = None
    one_of_schemas: Set[str] = { "InitiateRemoteUpload201ResponseOneOf", "Media" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = InitiateRemoteUpload201Response.model_construct()
        error_messages = []
        match = 0
        # validate data type: Media
        if not isinstance(v, Media):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Media`")
        else:
            match += 1
        # validate data type: InitiateRemoteUpload201ResponseOneOf
        if not isinstance(v, InitiateRemoteUpload201ResponseOneOf):
            error_messages.append(f"Error! Input type `{type(v)}` is not `InitiateRemoteUpload201ResponseOneOf`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in InitiateRemoteUpload201Response with oneOf schemas: InitiateRemoteUpload201ResponseOneOf, Media. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in InitiateRemoteUpload201Response with oneOf schemas: InitiateRemoteUpload201ResponseOneOf, Media. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into Media
        try:
            instance.actual_instance = Media.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into InitiateRemoteUpload201ResponseOneOf
        try:
            instance.actual_instance = InitiateRemoteUpload201ResponseOneOf.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into InitiateRemoteUpload201Response with oneOf schemas: InitiateRemoteUpload201ResponseOneOf, Media. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into InitiateRemoteUpload201Response with oneOf schemas: InitiateRemoteUpload201ResponseOneOf, Media. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], InitiateRemoteUpload201ResponseOneOf, Media]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


