# coding: utf-8

"""
    PostBoost API

    The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

    The version of the OpenAPI document: 1.0.0
    Contact: hi@postboost.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from postboost.models.post_version import PostVersion
from typing import Optional, Set
from typing_extensions import Self

class PostInput(BaseModel):
    """
    PostInput
    """ # noqa: E501
    versions: Annotated[List[PostVersion], Field(min_length=1)] = Field(description="At least one version with `is_original: true` is required.")
    accounts: Optional[List[StrictInt]] = Field(default=None, description="Account IDs to publish to.")
    tags: Optional[List[StrictInt]] = Field(default=None, description="Tag IDs to attach.")
    var_date: Optional[date] = Field(default=None, alias="date")
    time: Optional[StrictStr] = None
    timezone: Optional[StrictStr] = None
    schedule: Optional[StrictBool] = Field(default=None, description="Schedule the post for the given date/time.")
    schedule_now: Optional[StrictBool] = Field(default=None, description="Publish immediately.")
    queue: Optional[StrictBool] = Field(default=None, description="Add to the smart publishing queue.")
    __properties: ClassVar[List[str]] = ["versions", "accounts", "tags", "date", "time", "timezone", "schedule", "schedule_now", "queue"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PostInput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in versions (list)
        _items = []
        if self.versions:
            for _item_versions in self.versions:
                if _item_versions:
                    _items.append(_item_versions.to_dict())
            _dict['versions'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PostInput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "versions": [PostVersion.from_dict(_item) for _item in obj["versions"]] if obj.get("versions") is not None else None,
            "accounts": obj.get("accounts"),
            "tags": obj.get("tags"),
            "date": obj.get("date"),
            "time": obj.get("time"),
            "timezone": obj.get("timezone"),
            "schedule": obj.get("schedule"),
            "schedule_now": obj.get("schedule_now"),
            "queue": obj.get("queue")
        })
        return _obj


