# coding: utf-8

"""
    PostBoost API

    The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

    The version of the OpenAPI document: 1.0.0
    Contact: hi@postboost.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class SubscriptionStatus(str, Enum):
    """
    SubscriptionStatus
    """

    """
    allowed enum values
    """
    ACTIVE = 'active'
    TRIALING = 'trialing'
    PAST_DUE = 'past_due'
    PAUSED = 'paused'
    CANCELED = 'canceled'
    INCOMPLETE = 'incomplete'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SubscriptionStatus from a JSON string"""
        return cls(json.loads(json_str))


